### ISSUE TITLE
Wrong hash table usage.

### ISSUE THREAD

**Issue by mohammad-alwa** [yaapc/php_comp#10]
[https://github.com/yaapc/php_comp/blob/master/src/grammar.y#L516-L546](https://github.com/yaapc/php_comp/blob/master/src/grammar.y#L516-L546)

```


class_declaration_statement:
        class_entry_type T_STRING extends_from implements_list open_par class_statement_list close_par
        {
            pl.log("class:", 0); pl.log($<r.str>2);
            symbolsParser->finishClassInsertion($<r.str>2, $<r.str>3, dynamic_cast<Class*>($<Symbol>1), $<Scope>5);
            $<Symbol>$ = symbolsParser->getCurrentClassSym();
            symbolsParser->popFromClassesStack();
        }
...........................
;

class_entry_type:
        T_CLASS
        {
            ...............
            Class* classSym = new Class($<r.col_no>1, $<r.line_no>1, false,false);
            $<Symbol>$ = symbolsParser->insertSymbol(classSym);
            //symbolsParser->setCurrentClassSym(classSym);
            symbolsParser->pushToClassesStack(classSym);
        }
```

The class symbol is instantiated in `class_entry_type`. And then it's inserted into the symbol table. At this stage, the symbol doesn't has a name. In the `Class` constructor, it's assigned an empty string.
In `class_declaration_statement`, the class symbol gets its name.
But the symbol table depends on the name of the symbol as a key in the hash table. So the class symbol can be retrieved using the empty string, not its name. If we tried retrieving it by its name, we can't. It's stored in the empty string bucket.

**Comment by bass3l** [comment]
you are right.
a solution might be is to pull class's "T_STRING" back to the rule where we instantiate a ClassSymbol with its proper name.
