### ISSUE TITLE
SymbolTable for-initialization list problem

### ISSUE THREAD

**Issue by bass3l** [yaapc/php_comp#8]
the **for-initialization list**  is the _for_expr_ rules the parser parse :

```
for_loop:
      for_loop_start '(' for_expr ';'  for_expr ';' for_expr ')' for_statement
;
```

the scope is initialized in the **for_statement** rule.

the problem is that the variables ( counters ) declared will not be in the scope of the **for-body**.
this issue is easily resolved by inserting those variables into the scope after the body has been reduced in the **for_loop** semantic action.

but the problem is that the insertion is done after the body has been parsed,that means. every occurrence of one of the counters inside the body will be reported as undefined.

**Comment by mohammad-alwa** [comment]
Initialize the scope in _for_loop_start_.

**Comment by bass3l** [comment]
- initialized the scope int for_loop_start 
- added a `forLoopFlag` as a boolean to skip creating a scope in `for_statement`
